// Actions Types

// List
export const LIST_REQUEST = 'JOB/LIST/REQUEST'
export const LIST_RESPONSE = 'JOB/LIST/RESPONSE'
export const LIST_DONE = 'JOB/LIST/DONE'
export const LIST_RESET = 'JOB/LIST/RESET'

// Single
export const SINGLE_REQUEST = 'JOB/SINGLE/REQUEST'
export const SINGLE_RESPONSE = 'JOB/SINGLE/RESPONSE'
export const SINGLE_DONE = 'JOB/SINGLE/DONE'
export const SINGLE_RESET = 'JOB/SINGLE/RESET'

// List by project
export const LIST_BY_PROJECT_REQUEST = 'JOB/LIST/BY_PROJECT/REQUEST'
export const LIST_BY_PROJECT_RESPONSE = 'JOB/LIST/BY_PROJECT/RESPONSE'
export const LIST_BY_PROJECT_DONE = 'JOB/LIST/BY_PROJECT/DONE'
export const LIST_BY_PROJECT_RESET = 'JOB/LIST/BY_PROJECT/RESET'

// Edit
export const EDIT_SET = 'JOB/EDIT/SET'
export const EDIT_UNSET = 'JOB/EDIT/UNSET'

// View
export const VIEW_SET = 'JOB/VIEW/SET'
export const VIEW_UNSET = 'JOB/VIEW/UNSET'
export const VIEW_HIDE = 'JOB/VIEW/HIDE'
