// Actions Types

// List
export const LIST_REQUEST = 'PROJECT/LIST/REQUEST'
export const LIST_RESPONSE = 'PROJECT/LIST/RESPONSE'
export const LIST_DONE = 'PROJECT/LIST/DONE'
export const LIST_RESET = 'PROJECT/LIST/RESET'

// Single
export const SINGLE_REQUEST = 'PROJECT/SINGLE/REQUEST'
export const SINGLE_RESPONSE = 'PROJECT/SINGLE/RESPONSE'
export const SINGLE_DONE = 'PROJECT/SINGLE/DONE'
export const SINGLE_RESET = 'PROJECT/SINGLE/RESET'

// Edit
export const EDIT_SET = 'PROJECT/EDIT_SET'
export const EDIT_UNSET = 'PROJECT/EDIT_UNSET'

// Dashboard
export const DASHBOARD_SET = 'PROJECT/DASHBOARD_SET'
export const DASHBOARD_UNSET = 'PROJECT/DASHBOARD_UNSET'
