
export const CANDIDATE_LIST_CACHE = 'CACHE.KEY.CANDIDATE.LIST'
export const CANDIDATE_SINGLE_CACHE = 'CACHE.KEY.CANDIDATE.SINGLE'
export const CANDIDATE_LIST_BY_PROJECT_CACHE = 'CACHE.KEY.CANDIDATE.LIST.BY.PROJECT'
