// Actions Types

// List
export const LIST_REQUEST = 'CANDIDATE/LIST/REQUEST'
export const LIST_RESPONSE = 'CANDIDATE/LIST/RESPONSE'
export const LIST_DONE = 'CANDIDATE/LIST/DONE'
export const LIST_RESET = 'CANDIDATE/LIST/RESET'

// Single
export const SINGLE_REQUEST = 'CANDIDATE/SINGLE/REQUEST'
export const SINGLE_RESPONSE = 'CANDIDATE/SINGLE/RESPONSE'
export const SINGLE_DONE = 'CANDIDATE/SINGLE/DONE'
export const SINGLE_RESET = 'CANDIDATE/SINGLE/RESET'

// List by client
export const LIST_BY_CLIENT_REQUEST = 'CANDIDATE/LIST/BY_CLIENT/REQUEST'
export const LIST_BY_CLIENT_RESPONSE = 'CANDIDATE/LIST/BY_CLIENT/RESPONSE'
export const LIST_BY_CLIENT_DONE = 'CANDIDATE/LIST/BY_CLIENT/DONE'
export const LIST_BY_CLIENT_RESET = 'CANDIDATE/LIST/BY_CLIENT/RESET'

// Edit
export const EDIT_SET = 'CANDIDATE/EDIT/SET'
export const EDIT_UNSET = 'CANDIDATE/EDIT/UNSET'

// View
export const VIEW_SET = 'CANDIDATE/VIEW/SET'
export const VIEW_UNSET = 'CANDIDATE/VIEW/UNSET'
export const VIEW_HIDE = 'CANDIDATE/VIEW/HIDE'
