// Actions Types

// List
export const CANDIDATES_GET_LIST_REQUEST = 'CANDIDATES/GET_LIST_REQUEST'
export const CANDIDATES_GET_LIST_RESPONSE = 'CANDIDATES/GET_LIST_RESPONSE'
export const CANDIDATES_GET_LIST_DONE = 'CANDIDATES/GET_LIST_DONE'
export const CANDIDATES_GET_LIST_RESET = 'CANDIDATES/GET_LIST_RESET'

// List by client
export const CANDIDATES_GET_LIST_BY_CLIENT_REQUEST = 'CANDIDATES/GET_LIST_BY_CLIENT_REQUEST'
export const CANDIDATES_GET_LIST_BY_CLIENT_RESPONSE = 'CANDIDATES/GET_LIST_BY_CLIENT_RESPONSE'
export const CANDIDATES_GET_LIST_BY_CLIENT_DONE = 'CANDIDATES/GET_LIST_BY_CLIENT_DONE'
export const CANDIDATES_GET_LIST_BY_CLIENT_RESET = 'CANDIDATES/GET_LIST_BY_CLIENT_RESET'

// Single
export const CANDIDATE_GET_REQUEST = 'CANDIDATE/GET_REQUEST'
export const CANDIDATE_GET_RESPONSE = 'CANDIDATE/GET_RESPONSE'
export const CANDIDATE_GET_DONE = 'CANDIDATE/GET_DONE'
export const CANDIDATE_GET_RESET = 'CANDIDATE/GET_RESET'

// Edit
export const CANDIDATE_EDIT_SET = 'CANDIDATE/EDIT_SET'
export const CANDIDATE_EDIT_UNSET = 'CANDIDATE/EDIT_UNSET'
