export const ACTIVITY_LIST_BY_ORGANIZATION_CACHE = 'CACHE.KEY.ACTIVITY.LIST.BY.ORGANIZATION'
export const ACTIVITY_LIST_BY_PROJECT_CACHE = 'CACHE.KEY.ACTIVITY.LIST.BY.PROJECT'
export const ACTIVITY_LIST_BY_CANDIDATE_CACHE = 'CACHE.KEY.ACTIVITY.LIST.BY.CANDIDATE'
