// Actions Types

// List by project
export const LIST_BY_ORGANIZATION_REQUEST = 'KANBAN/LIST/BY_ORGANIZATION/REQUEST'
export const LIST_BY_ORGANIZATION_RESPONSE = 'KANBAN/LIST/BY_ORGANIZATION/RESPONSE'
export const LIST_BY_ORGANIZATION_DONE = 'KANBAN/LIST/BY_ORGANIZATION/DONE'
export const LIST_BY_ORGANIZATION_RESET = 'KANBAN/LIST/BY_ORGANIZATION/RESET'


// List by project
export const LIST_BY_PROJECT_REQUEST = 'KANBAN/LIST/BY_PROJECT/REQUEST'
export const LIST_BY_PROJECT_RESPONSE = 'KANBAN/LIST/BY_PROJECT/RESPONSE'
export const LIST_BY_PROJECT_DONE = 'KANBAN/LIST/BY_PROJECT/DONE'
export const LIST_BY_PROJECT_RESET = 'KANBAN/LIST/BY_PROJECT/RESET'


// List by candidate
export const LIST_BY_CANDIDATE_REQUEST = 'KANBAN/LIST/BY_CANDIDATE/REQUEST'
export const LIST_BY_CANDIDATE_RESPONSE = 'KANBAN/LIST/BY_CANDIDATE/RESPONSE'
export const LIST_BY_CANDIDATE_DONE = 'KANBAN/LIST/BY_CANDIDATE/DONE'
export const LIST_BY_CANDIDATE_RESET = 'KANBAN/LIST/BY_CANDIDATE/RESET'

