// Actions Types

// List by client
export const LIST_BY_ORGANIZATION_REQUEST = 'KANBAN/LIST/BY_ORGANIZATION/REQUEST'
export const LIST_BY_ORGANIZATION_RESPONSE = 'KANBAN/LIST/BY_ORGANIZATION/RESPONSE'
export const LIST_BY_ORGANIZATION_DONE = 'KANBAN/LIST/BY_ORGANIZATION/DONE'
export const LIST_BY_ORGANIZATION_RESET = 'KANBAN/LIST/BY_ORGANIZATION/RESET'


// List by client
export const LIST_BY_CLIENT_REQUEST = 'KANBAN/LIST/BY_CLIENT/REQUEST'
export const LIST_BY_CLIENT_RESPONSE = 'KANBAN/LIST/BY_CLIENT/RESPONSE'
export const LIST_BY_CLIENT_DONE = 'KANBAN/LIST/BY_CLIENT/DONE'
export const LIST_BY_CLIENT_RESET = 'KANBAN/LIST/BY_CLIENT/RESET'

