// Actions Types

// List
export const LIST_REQUEST = 'CLIENT/LIST/REQUEST'
export const LIST_RESPONSE = 'CLIENT/LIST/RESPONSE'
export const LIST_DONE = 'CLIENT/LIST/DONE'
export const LIST_RESET = 'CLIENT/LIST/RESET'

// Single
export const SINGLE_REQUEST = 'CLIENT/SINGLE/REQUEST'
export const SINGLE_RESPONSE = 'CLIENT/SINGLE/RESPONSE'
export const SINGLE_DONE = 'CLIENT/SINGLE/DONE'
export const SINGLE_RESET = 'CLIENT/SINGLE/RESET'

// Edit
export const EDIT_SET = 'CLIENT/EDIT_SET'
export const EDIT_UNSET = 'CLIENT/EDIT_UNSET'

// Dashboard
export const DASHBOARD_SET = 'CLIENT/DASHBOARD_SET'
export const DASHBOARD_UNSET = 'CLIENT/DASHBOARD_UNSET'
