// Actions Types

// List
export const LIST_REQUEST = 'PANEL/LIST/REQUEST'
export const LIST_RESPONSE = 'PANEL/LIST/RESPONSE'
export const LIST_DONE = 'PANEL/LIST/DONE'
export const LIST_RESET = 'PANEL/LIST/RESET'

// Single
export const SINGLE_REQUEST = 'PANEL/SINGLE/REQUEST'
export const SINGLE_RESPONSE = 'PANEL/SINGLE/RESPONSE'
export const SINGLE_DONE = 'PANEL/SINGLE/DONE'
export const SINGLE_RESET = 'PANEL/SINGLE/RESET'

// List by client
export const LIST_BY_CLIENT_REQUEST = 'PANEL/LIST/BY_CLIENT/REQUEST'
export const LIST_BY_CLIENT_RESPONSE = 'PANEL/LIST/BY_CLIENT/RESPONSE'
export const LIST_BY_CLIENT_DONE = 'PANEL/LIST/BY_CLIENT/DONE'
export const LIST_BY_CLIENT_RESET = 'PANEL/LIST/BY_CLIENT/RESET'

// Edit
export const EDIT_SET = 'PANEL/EDIT_SET'
export const EDIT_UNSET = 'PANEL/EDIT_UNSET'
