
export const INTERVIEW_LIST_CACHE = 'CACHE.KEY.INTERVIEW.LIST'
export const INTERVIEW_SINGLE_CACHE = 'CACHE.KEY.INTERVIEW.SINGLE'
export const INTERVIEW_LIST_BY_CLIENT_CACHE = 'CACHE.KEY.INTERVIEW.LIST.BY.CLIENT'
