// Actions Types

// Single
export const SINGLE_REQUEST = 'INTERVIEW/SINGLE/REQUEST'
export const SINGLE_RESPONSE = 'INTERVIEW/SINGLE/RESPONSE'
export const SINGLE_DONE = 'INTERVIEW/SINGLE/DONE'
export const SINGLE_RESET = 'INTERVIEW/SINGLE/RESET'

// List by project
export const LIST_BY_PROJECT_REQUEST = 'INTERVIEW/LIST/BY_PROJECT/REQUEST'
export const LIST_BY_PROJECT_RESPONSE = 'INTERVIEW/LIST/BY_PROJECT/RESPONSE'
export const LIST_BY_PROJECT_DONE = 'INTERVIEW/LIST/BY_PROJECT/DONE'
export const LIST_BY_PROJECT_RESET = 'INTERVIEW/LIST/BY_PROJECT/RESET'

// Edit
export const EDIT_SET = 'INTERVIEW/EDIT_SET'
export const EDIT_UNSET = 'INTERVIEW/EDIT_UNSET'

// View
export const VIEW_SET = 'INTERVIEW/VIEW/SET'
export const VIEW_UNSET = 'INTERVIEW/VIEW/UNSET'
export const VIEW_HIDE = 'INTERVIEW/VIEW/HIDE'
