// Actions Types

// Single
export const SINGLE_REQUEST = 'KANBAN/SINGLE/REQUEST'
export const SINGLE_RESPONSE = 'KANBAN/SINGLE/RESPONSE'
export const SINGLE_DONE = 'KANBAN/SINGLE/DONE'
export const SINGLE_RESET = 'KANBAN/SINGLE/RESET'

// List by project
export const LIST_BY_PROJECT_REQUEST = 'KANBAN/LIST/BY_PROJECT/REQUEST'
export const LIST_BY_PROJECT_RESPONSE = 'KANBAN/LIST/BY_PROJECT/RESPONSE'
export const LIST_BY_PROJECT_DONE = 'KANBAN/LIST/BY_PROJECT/DONE'
export const LIST_BY_PROJECT_RESET = 'KANBAN/LIST/BY_PROJECT/RESET'

