// Actions Types

// List
export const LIST_REQUEST = 'KANBAN/LIST/REQUEST'
export const LIST_RESPONSE = 'KANBAN/LIST/RESPONSE'
export const LIST_DONE = 'KANBAN/LIST/DONE'
export const LIST_RESET = 'KANBAN/LIST/RESET'

// Single
export const SINGLE_REQUEST = 'KANBAN/SINGLE/REQUEST'
export const SINGLE_RESPONSE = 'KANBAN/SINGLE/RESPONSE'
export const SINGLE_DONE = 'KANBAN/SINGLE/DONE'
export const SINGLE_RESET = 'KANBAN/SINGLE/RESET'

// List by client
export const LIST_BY_CLIENT_REQUEST = 'KANBAN/LIST/BY_CLIENT/REQUEST'
export const LIST_BY_CLIENT_RESPONSE = 'KANBAN/LIST/BY_CLIENT/RESPONSE'
export const LIST_BY_CLIENT_DONE = 'KANBAN/LIST/BY_CLIENT/DONE'
export const LIST_BY_CLIENT_RESET = 'KANBAN/LIST/BY_CLIENT/RESET'

