
export const INTERVIEWER_LIST_CACHE = 'CACHE.KEY.INTERVIEWER.LIST'
export const INTERVIEWER_SINGLE_CACHE = 'CACHE.KEY.INTERVIEWER.SINGLE'
export const INTERVIEWER_LIST_BY_CLIENT_CACHE = 'CACHE.KEY.INTERVIEWER.LIST.BY.CLIENT'
