// Actions Types

// List
export const LIST_REQUEST = 'INTERVIEWER/LIST/REQUEST'
export const LIST_RESPONSE = 'INTERVIEWER/LIST/RESPONSE'
export const LIST_DONE = 'INTERVIEWER/LIST/DONE'
export const LIST_RESET = 'INTERVIEWER/LIST/RESET'

// Single
export const SINGLE_REQUEST = 'INTERVIEWER/SINGLE/REQUEST'
export const SINGLE_RESPONSE = 'INTERVIEWER/SINGLE/RESPONSE'
export const SINGLE_DONE = 'INTERVIEWER/SINGLE/DONE'
export const SINGLE_RESET = 'INTERVIEWER/SINGLE/RESET'

// List by project
export const LIST_BY_PROJECT_REQUEST = 'INTERVIEWER/LIST/BY_PROJECT/REQUEST'
export const LIST_BY_PROJECT_RESPONSE = 'INTERVIEWER/LIST/BY_PROJECT/RESPONSE'
export const LIST_BY_PROJECT_DONE = 'INTERVIEWER/LIST/BY_PROJECT/DONE'
export const LIST_BY_PROJECT_RESET = 'INTERVIEWER/LIST/BY_PROJECT/RESET'

// Edit
export const EDIT_SET = 'INTERVIEWER/EDIT_SET'
export const EDIT_UNSET = 'INTERVIEWER/EDIT_UNSET'
