// Actions Types

// List
export const LIST_REQUEST = 'ORGANIZATION/LIST/REQUEST'
export const LIST_RESPONSE = 'ORGANIZATION/LIST/RESPONSE'
export const LIST_DONE = 'ORGANIZATION/LIST/DONE'
export const LIST_RESET = 'ORGANIZATION/LIST/RESET'

// Single
export const SINGLE_REQUEST = 'ORGANIZATION/SINGLE/REQUEST'
export const SINGLE_RESPONSE = 'ORGANIZATION/SINGLE/RESPONSE'
export const SINGLE_DONE = 'ORGANIZATION/SINGLE/DONE'
export const SINGLE_RESET = 'ORGANIZATION/SINGLE/RESET'

